// <auto-generated />
using System;
using System.Collections.Generic;
using BergerDb.Persistanse;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BergerDb.Persistanse.Migrations
{
    [DbContext(typeof(BergerDbContext))]
    [Migration("20241230030504_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BergerDb.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entry_type");

                    b.Property<int>("MemberType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_type");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_type");

                    b.Property<long>("PersonalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("personal_id");

                    b.Property<DateTime>("RegisteredOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("registrated_on");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sex");

                    b.Property<decimal>("SubscriptionCost")
                        .HasColumnType("TEXT")
                        .HasColumnName("subscription_cost");

                    b.Property<DateTime?>("TerminatedOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminated_on");

                    b.ComplexProperty<Dictionary<string, object>>("Street", "BergerDb.Domain.Customers.Customer.Street#Street", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("address");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "BergerDb.Domain.Customers.Customer.Email#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "BergerDb.Domain.Customers.Customer.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("first_name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Institution", "BergerDb.Domain.Customers.Customer.Institution#Institution", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("institution");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LastName", "BergerDb.Domain.Customers.Customer.LastName#LastName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("last_name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Notation", "BergerDb.Domain.Customers.Customer.Notation#Notation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3000)
                                .HasColumnType("TEXT")
                                .HasColumnName("notation");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Prefix", "BergerDb.Domain.Customers.Customer.Prefix#Prefix", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("prefix");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ZipCode", "BergerDb.Domain.Customers.Customer.ZipCode#ZipCode", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("zip_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.Emails.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body_text");

                    b.Property<int>("EmailType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_type");

                    b.Property<DateTime>("SentOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("sent_on");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.ComplexProperty<Dictionary<string, object>>("From", "BergerDb.Domain.Emails.Email.From#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("from");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PdfMetadata", "BergerDb.Domain.Emails.Email.PdfMetadata#PdfMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("pdf_metadata_file_name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("To", "BergerDb.Domain.Emails.Email.To#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("to");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("emails", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.PaymentProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_process_payment_type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("payment_process", (string)null);

                    b.HasDiscriminator<int>("PaymentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BergerDb.Domain.Payments.PaymentId", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("paid_on");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.PdfTemplates.PdfTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pdf_template_color");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("pdf_templates", (string)null);
                });

            modelBuilder.Entity("EmailPaymentProcess", b =>
                {
                    b.Property<Guid>("EmailsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentProcessId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmailsId", "PaymentProcessId");

                    b.HasIndex("PaymentProcessId");

                    b.ToTable("EmailPaymentProcess");
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.Billing", b =>
                {
                    b.HasBaseType("BergerDb.Domain.PaymentProcesses.PaymentProcess");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.Debiting", b =>
                {
                    b.HasBaseType("BergerDb.Domain.PaymentProcesses.PaymentProcess");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.PaymentProcess", b =>
                {
                    b.HasOne("BergerDb.Domain.Customers.Customer", null)
                        .WithMany("PaymentProcesses")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("BergerDb.Domain.Payments.PaymentId", b =>
                {
                    b.HasOne("BergerDb.Domain.PaymentProcesses.PaymentProcess", "PaymentProcess")
                        .WithOne("PaymentId")
                        .HasForeignKey("BergerDb.Domain.Payments.PaymentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentProcess");
                });

            modelBuilder.Entity("EmailPaymentProcess", b =>
                {
                    b.HasOne("BergerDb.Domain.Emails.Email", null)
                        .WithMany()
                        .HasForeignKey("EmailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BergerDb.Domain.PaymentProcesses.PaymentProcess", null)
                        .WithMany()
                        .HasForeignKey("PaymentProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Customer", b =>
                {
                    b.Navigation("PaymentProcesses");
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.PaymentProcess", b =>
                {
                    b.Navigation("PaymentId");
                });
#pragma warning restore 612, 618
        }
    }
}
