// <auto-generated />
using System;
using System.Collections.Generic;
using BergerDb.Persistanse;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BergerDb.Persistanse.Migrations
{
    [DbContext(typeof(BergerDbContext))]
    [Migration("20250224191350_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BergerDb.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PersonalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubscriptionCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminatedOnUtc")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("City", "BergerDb.Domain.Customers.Customer.City#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("EmailAddress", "BergerDb.Domain.Customers.Customer.EmailAddress#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FirstName", "BergerDb.Domain.Customers.Customer.FirstName#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Institution", "BergerDb.Domain.Customers.Customer.Institution#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LastName", "BergerDb.Domain.Customers.Customer.LastName#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Notation", "BergerDb.Domain.Customers.Customer.Notation#Notation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3000)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Prefix", "BergerDb.Domain.Customers.Customer.Prefix#Prefix", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Street", "BergerDb.Domain.Customers.Customer.Street#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ZipCode", "BergerDb.Domain.Customers.Customer.ZipCode#ZipCode", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.Emails.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaymentProcessId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("From", "BergerDb.Domain.Emails.Email.From#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PdfMetadata", "BergerDb.Domain.Emails.Email.PdfMetadata#PdfMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("To", "BergerDb.Domain.Emails.Email.To#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PaymentProcessId");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.PaymentProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("PaymentProcesses", (string)null);

                    b.HasDiscriminator<int>("PaymentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BergerDb.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentProcessId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PaymentProcessId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.PdfTemplates.PdfTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("PdfTemplates", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.Billing", b =>
                {
                    b.HasBaseType("BergerDb.Domain.PaymentProcesses.PaymentProcess");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.Debiting", b =>
                {
                    b.HasBaseType("BergerDb.Domain.PaymentProcesses.PaymentProcess");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BergerDb.Domain.Emails.Email", b =>
                {
                    b.HasOne("BergerDb.Domain.PaymentProcesses.PaymentProcess", null)
                        .WithMany("Emails")
                        .HasForeignKey("PaymentProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.PaymentProcess", b =>
                {
                    b.HasOne("BergerDb.Domain.Customers.Customer", null)
                        .WithMany("PaymentProcesses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BergerDb.Domain.Payments.Payment", null)
                        .WithOne()
                        .HasForeignKey("BergerDb.Domain.PaymentProcesses.PaymentProcess", "PaymentId");
                });

            modelBuilder.Entity("BergerDb.Domain.Payments.Payment", b =>
                {
                    b.HasOne("BergerDb.Domain.PaymentProcesses.PaymentProcess", null)
                        .WithOne()
                        .HasForeignKey("BergerDb.Domain.Payments.Payment", "PaymentProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Customer", b =>
                {
                    b.Navigation("PaymentProcesses");
                });

            modelBuilder.Entity("BergerDb.Domain.PaymentProcesses.PaymentProcess", b =>
                {
                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
