// <auto-generated />
using System;
using BergerDb.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BergerDb.Persistence.Migrations
{
    [DbContext(typeof(BergerDbContext))]
    [Migration("20240131204623_Added_refund_date")]
    partial class Added_refund_date
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BergerDb.Domain.Customers.Addresses.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("PersonalId")
                        .HasColumnType("bigint")
                        .HasColumnName("personal_id");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Memberships.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer")
                        .HasColumnName("entry_type");

                    b.Property<bool>("IsRecivedEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recived_email");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer")
                        .HasColumnName("member_type");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.Property<DateTime?>("RefundedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_on");

                    b.Property<DateTime?>("TerminatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_on");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.Users.EmailConfigurations.EmailConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("email_configuration_id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<string>("AdmonitionEmailBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admonition_email_body");

                    b.Property<string>("AdmonitionSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admonition_subject");

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bic");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gid");

                    b.Property<string>("HomePage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_page");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<string>("InvoiceEmailBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_email_body");

                    b.Property<string>("InvoicePdfBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_pdf_body");

                    b.Property<string>("InvoiceSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_subject");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tax_identification_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postalcode");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("email_configuration", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.Users.Permissions.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_name");

                    b.HasKey("Id");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "UsersCreate"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "UsersRead"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "UsersUpdate"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "UsersDelete"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "CustomersCreate"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "CustomersRead"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "CustomersUpdate"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "CustomersDelete"
                        });
                });

            modelBuilder.Entity("BergerDb.Domain.Users.RolePermissions.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 2L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 7L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 8L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 6L
                        });
                });

            modelBuilder.Entity("BergerDb.Domain.Users.Roles.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Visitor"
                        });
                });

            modelBuilder.Entity("BergerDb.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character(256)")
                        .HasColumnName("password_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Addresses.Address", b =>
                {
                    b.HasOne("BergerDb.Domain.Customers.Customer", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("BergerDb.Domain.Customers.Addresses.Address", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BergerDb.Domain.Customers.Addresses.AddressNames.AddressName", "City", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.HasKey("AddressId");

                            b1.ToTable("addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.OwnsOne("BergerDb.Domain.Customers.Addresses.AddressNames.AddressName", "Street", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");

                            b1.HasKey("AddressId");

                            b1.ToTable("addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.OwnsOne("BergerDb.Domain.Customers.Addresses.PostalCodes.ZipCode", "ZipCode", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("zip_code");

                            b1.HasKey("AddressId");

                            b1.ToTable("addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.Navigation("City")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Street")
                        .IsRequired();

                    b.Navigation("ZipCode")
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("BergerDb.Domain.Shared.Email.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("BergerDb.Domain.Shared.FirstNames.FirstName", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("BergerDb.Domain.Shared.LastNames.LastName", "LastName", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("BergerDb.Domain.Customers.NameTitles.Prefix", "Prefix", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("prefix");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("BergerDb.Domain.Customers.Notations.Notation", "Notation", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3000)
                                .HasColumnType("character varying(3000)")
                                .HasColumnName("notation");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("Notation")
                        .IsRequired();

                    b.Navigation("Prefix")
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Memberships.Membership", b =>
                {
                    b.HasOne("BergerDb.Domain.Customers.Customer", "Customer")
                        .WithOne("Membership")
                        .HasForeignKey("BergerDb.Domain.Customers.Memberships.Membership", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BergerDb.Domain.Customers.Memberships.Institutions.Institution", "Institution", b1 =>
                        {
                            b1.Property<Guid>("MembershipId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("institution");

                            b1.HasKey("MembershipId");

                            b1.ToTable("memberships");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.OwnsOne("BergerDb.Domain.Shared.DateRanges.InvoiceDateRange", "CreditReceivedOn", b1 =>
                        {
                            b1.Property<Guid>("MembershipId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("Current")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("current_credit_received_on");

                            b1.Property<DateTime?>("Last")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_credit_received_on");

                            b1.HasKey("MembershipId");

                            b1.ToTable("memberships");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.OwnsOne("BergerDb.Domain.Shared.DateRanges.InvoiceDateRange", "InvoiceSendedOn", b1 =>
                        {
                            b1.Property<Guid>("MembershipId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("Current")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("current_invoice_sended_on");

                            b1.Property<DateTime?>("Last")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_invoice_sended_on");

                            b1.HasKey("MembershipId");

                            b1.ToTable("memberships");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.Navigation("CreditReceivedOn")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Institution")
                        .IsRequired();

                    b.Navigation("InvoiceSendedOn")
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.Users.EmailConfigurations.EmailConfiguration", b =>
                {
                    b.HasOne("BergerDb.Domain.Users.User", "User")
                        .WithOne("EmailConfiguration")
                        .HasForeignKey("BergerDb.Domain.Users.EmailConfigurations.EmailConfiguration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BergerDb.Domain.Users.RolePermissions.RolePermission", b =>
                {
                    b.HasOne("BergerDb.Domain.Users.Permissions.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BergerDb.Domain.Users.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.Users.User", b =>
                {
                    b.OwnsOne("BergerDb.Domain.Shared.Email.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("BergerDb.Domain.Shared.FirstNames.FirstName", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("BergerDb.Domain.Shared.LastNames.LastName", "LastName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("BergerDb.Domain.Users.UserNames.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("user_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FirstName");

                    b.Navigation("LastName");

                    b.Navigation("UserName")
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("BergerDb.Domain.Users.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BergerDb.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BergerDb.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("BergerDb.Domain.Users.User", b =>
                {
                    b.Navigation("EmailConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
