CREATE TABLE IF NOT EXISTS customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    personalId BIGINT NOT NULL UNIQUE,
    prefix TEXT NOT NULL,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    sex INTEGER NOT NULL CHECK (sex IN (0, 1, 2)),
    email TEXT NOT NULL CHECK (email LIKE '%@%.%'),
    registeredOnUtc BIGINT NOT NULL,
    terminatedOnUtc BIGINT,
    notation TEXT NOT NULL,
    street TEXT NOT NULL,
    city TEXT NOT NULL,
    zipCode TEXT NOT NULL,
    paymentType INTEGER NOT NULL CHECK (paymentType >= 0),
    memberType INTEGER NOT NULL CHECK (memberType >= 0),
    entryType INTEGER NOT NULL CHECK (entryType >= 0),
    subscriptionCost REAL NOT NULL CHECK (subscriptionCost >= 0),
    institution TEXT NOT NULL);